// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhg5DuxUzvadthFwiIat7P8N4XJRGO8Ro',
    appId: '1:198364607453:web:b9908e745f15acf3987c34',
    messagingSenderId: '198364607453',
    projectId: 'arriendapp-22150',
    authDomain: 'arriendapp-22150.firebaseapp.com',
    storageBucket: 'arriendapp-22150.firebasestorage.app',
    measurementId: 'G-KRY9B9FR76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgdCCzJMqzcGHguI5CJZhrko3-ZfbmoM',
    appId: '1:198364607453:android:6fe3fa0dc7806155987c34',
    messagingSenderId: '198364607453',
    projectId: 'arriendapp-22150',
    storageBucket: 'arriendapp-22150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Lvz3WXvE2X4Xy0bWAgjXX2RegwoqMVk',
    appId: '1:198364607453:ios:ad0d1c598b13bc27987c34',
    messagingSenderId: '198364607453',
    projectId: 'arriendapp-22150',
    storageBucket: 'arriendapp-22150.firebasestorage.app',
    iosBundleId: 'com.example.arriendapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Lvz3WXvE2X4Xy0bWAgjXX2RegwoqMVk',
    appId: '1:198364607453:ios:ad0d1c598b13bc27987c34',
    messagingSenderId: '198364607453',
    projectId: 'arriendapp-22150',
    storageBucket: 'arriendapp-22150.firebasestorage.app',
    iosBundleId: 'com.example.arriendapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhg5DuxUzvadthFwiIat7P8N4XJRGO8Ro',
    appId: '1:198364607453:web:3cb263b33f941116987c34',
    messagingSenderId: '198364607453',
    projectId: 'arriendapp-22150',
    authDomain: 'arriendapp-22150.firebaseapp.com',
    storageBucket: 'arriendapp-22150.firebasestorage.app',
    measurementId: 'G-2Y8CZG8F9R',
  );

}